# Generated by Django 3.0.8 on 2020-08-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('interest', models.TextField()),
                ('image', models.ImageField(upload_to='profile/image')),
            ],
        ),
    ]
