# Generated by Django 3.0.8 on 2020-08-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0002_education_language_skills_social'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
