# Generated by Django 3.0.8 on 2020-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_auto_20200809_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
