# Generated by Django 3.0.8 on 2020-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_user_profile_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
