# Generated by Django 3.0.8 on 2020-08-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0005_auto_20200809_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='last_name',
            new_name='lname',
        ),
    ]
