# Generated by Django 3.0.8 on 2020-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0006_auto_20200809_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
