# Generated by Django 3.0.8 on 2020-08-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0008_auto_20200809_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_yer',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_yer',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='results',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
