# Generated by Django 3.0.8 on 2020-08-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0009_auto_20200809_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='Userp',
        ),
    ]
