# Generated by Django 3.0.8 on 2020-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0010_auto_20200810_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None)),
            ],
        ),
    ]
