# Generated by Django 3.0.8 on 2020-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0012_experience_present_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='present_time',
            field=models.CharField(default='Present', max_length=50, null=True),
        ),
    ]
