# Generated by Django 3.0.8 on 2020-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0014_auto_20200810_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='present_time',
            field=models.CharField(blank=True, default='Present', max_length=50),
        ),
    ]
