# Generated by Django 3.0.8 on 2020-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0017_auto_20200810_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userp',
            name='ico',
            field=models.ImageField(blank=True, upload_to='profile/image'),
        ),
    ]
